var qa = {          
    "a":[
        ["Abbagnale","Chi sono i due piu celebri fratelli sportivi di Castellammare di Stabia?"],
        ["abramo","Il nome di Lincoln"],
        ["abramo","Quale era il nome di Abrahamo prima che Dio gli cambiasse nome?"],
        ["acerrimo","Superlativo di acre"],
        ["achille","Il suo punto debole era il tallone"],
        ["adamello","Massiccio montuoso delle Alpi Retiche, al confine tra la Lombardia e il Trentino-Alto Adige"],
        ["adisco","Presente indicativo di adire"],
        ["adolfo","Il nome del poeta Palazzeschi"],
        ["Adriatico","Quale mare separa l'Italia dalla ex-Jugoslavia?"],
        ["affrancare","Applicare il francobollo sulla busta"],
        ["afghanistan","Kabul ne e la capitale"],
        ["agatha christie","Uno dei suoi piu famosi libri parlava di 10 indiani..."],
        ["agnese",'Mamma di Lucia nei "Promessi Sposi"'],
        ["agricoltura","Secondo la mitologia romana Saturno era il dio della"],
        ["aida","Verdi la compose per l'apertura del canale di Suez"],
        ["alessandria","Ce n'e' una in Italia e una in Egitto"],
        ["alessandro","Il Cecchi Paone giornalista e conduttore"],
        ["alessandro manzoni",'Scrisse i "Promessi Sposi" (cognome).'],
        ["alisei","I venti che soffiano costantemente verso l'equatore"],
        ["ambra","Quale resina fossilizzata usavano Greci e Romani per fare giolielli?"],
        ["amedeo","Il Minghi della canzone italiana"],
        ["amelia","Come si chiama la strega in perenne lotta con Paperone"],
        ["amsterdam","Capitale dell'OLANDA"],
        ["anastacia","Cantante di: PAID MY DUES"],
        ["anco marzio","Quarto re di Roma"],
        ["andrea bocelli","Cantante di: VIVO PER LEI"],
        ["andrea doria","Come si chiamava il transatlantico italiano naufragato nel 1956 al largo della costa americana"],
        ["angela lansbury",'Interpreta "La signora in giallo"'],
        ["angelo branduardi","Cantante di: COGLI LA PRIMA MELA"],
        ["angelo branduardi","Cantante di: SI PUO' FARE"],
        ["anna","Il nome della Oxa"],
        ["antonello venditti","Cantante di: RICORDATI DI ME"],
        ["antonello venditti","Cantante di: GRAZIE ROMA"],
        ["arachide","Cosa mangia pippo per diventare superpippo"],
        ["argentina",'Ernesto "Che" Guevara era di nazionalita?'],
        ["argo","Il nome della nave di Giasone"],
        ["argonauti","Li comandava Giasone"],
        ["arianna","Teseo se ne innamora"],
        ["arno","Il fiume di Firenze"],
        ["Arsenio","Qual e il nome del ladro Lupin?"],
        ["artur conan doyle","Ha creato Scherlock Holmes"],
        ["atene","Capitale della GRECIA"],
        ["atene",'Vi si trova il "Partenone"']
 
    ],
    "b":[                
        ["babbo natale","Il famoso porta regali di natale"],
["Badalamenti","Il cognome di Tano ne I cento passi"],
["bagdad","Capitale dell'Iraq"],
["baltico","Il mare che bagna la lettonia"],
["bassano","Citta  veneta famosa per la grappa"],
["bassano","E' noto il suo ponte sul Brenta"],
["bassora","Seconda citta  dell'Iraq"],
["beppe","Il fratello di Fiorello (nome)"],
["beppe grillo","Il famoso comico genovese (nome e cognome)"],
["bergamotto","Qual e l'agrume che non si mangia, ma e preziosissimo per la sua essenza utilizzata nella fabbricazione dei cosmetici?"],
["berna","Vi lavorava Einstein a 26 anni (in svizzera)"],
//["bertè","Loredana cantante italiana"],
["betlemme","In quale citta del paese di Giudea nacque Gesu Cristo?"],
["biagio antonacci","Cantante di: IRIS"],
["biancaneve e i sette nani","Quale film Walt Disney realizzo nel 1937"],
["bratislava","La capitale della repubblica slovacca"],
["bruno",'Il Vespa che ha condotto "Porta a Porta"'],
["bruto","Il cattivo di Braccio di Ferro"],
["bruto","Uccise Giulio Cesare pugnalandolo"],
["budapest","Capitale dell'UNGHERIA"],
   ["balocchi","Il mitico paese del dolce far niente di Pinocchio"]
["Barbados","Bridgetown &egrave; la capitale di quale nazione?"]
    ],
    "c":[                
     ["camillo","Primo nome di Cavour"],
["Canna da zucchero","Da quale pianta si ottiene il Rum?"],
["caprera","Isola dove morì  Garibaldi"],
["capricorno","decimo sengo dello Zodiaco"],
["carattere","E' pessimo quello del bisbetico"],
["carlo","Il nome di Verdone"],
["carmen consoli","Cantante di: L'ULTIMO BACIO"],
["carotide","Grossa arteria che conduce il sangue alla testa"],
["cautela","Attenzione avvedutezza"],
["Cavalchina","Come si chiama il veglione del Venerdi Grasso al Carnevale di Venezia?"],
["celentano","Il supermolleggiato della canzone italiana"],
["cento","Quanti sono i canti della Divina Commedia"],
["centottanta","Qunati secondi ci sono in 3 minuti"],
["centoventi","Qunati secondi ci sono in 2 minuti"],
["charlie chaplin","Impersonava Charlot sul grande schermo"],
["cher","Cantante di: BELIEVE"],
["Cheyenne","Quale &egrave; la capitale dello stato Usa del Wyoming?"],
["christie","L'Agatha scrittrice di libri gialli"],
["ciccio","L'aiutante di nonna papera"],
["cinquanta","Quante stelle ha la bandiera USA?"],
["cinque","Quanti portici aveva la vasca chiamata Betesda che a Gerusalemme si trovava presso la porta delle pecore?"],
["cipollini","Il Mario vincitore del campionato mondiale di ciclismo su strada nel 2002"],
["claudio","Il Bisio comico italiano conduttore di Zelig"],
["claudio","L' attore Amendola"],
["claudio baglioni","Cantante di: STRADA FACENDO"],
["claustrofobia","Timore morboso degli spazi chiusi"],
["clavicembalo","Antenato del pianoforte"],
["co","Simbolo del Cobaldo"],
["cobra","Un serpente velenosissimo"],
["cocciante",'Il Riccardo di "Margherita"'],
["collins","Armstrong - Aldrin e..."],
["Colombia","Quale &egrave; il paese pi&ugrave; a nord dell'america del Sud?"],
["colombo",'Il famoso "Tenente" dei telefilm americani'],
["colori","Il bianco li racchiude tutti"],
["Concorde","Aereo civile che vola a due volte la velocitÃ  del suono"],
["concorde","Quale aereo poteva volare da Parigi a New York in 3 ore e 1/2"],
["contadini","Lavoratori dei campi"],
["copenaghen","Capitali europee : DANIMARCA"],
["copenhagen","DANIMARCA"],
["corner","Il nome inglese del calcio d'angolo"],
["corto","Il maltese nei fumetti"],
["cossiga",'Il "Francesco" picconatore e presidente della repubblica'],
["cristina d'avena","Canta canzoni di cartoni animati"],
      

    ],
    "d":[                
       ["Danimarca","Quale paese produce la birra Tuborg?"],
["Danimarca","In quale paese si svolge la storia di Amleto?"],
["d'arco","Fu bruciata su un rogo la Giovanna..."],
["decimo","Unit&ugrave;  di misura della potenza visiva"],
["dedalo","Costruì il labirinto di Minosse a Creta"],
["Delon","Chi era Rocco in Rocco e i suoi fratelli (cognome)?"],
["destra","Su quale riva del Nilo si trova Abu Simbel"],
["diabolik","Il ladro del fumetto italiano"],
["dino zoff","Il portiere della nazionale italiana del 1982"],
["dna","Acido desossiribonucleico"],
["doccia","&Eacute 'fredda' quando arriva una brutta notizia?"],
["dopobarba","Lo si mette sul viso dopo essersi fatti la barba"],
["dumas","Scrisse I tre Moschettieri"],
  

    ],   
    "e":[                
      ["Eboli","Dove si &egrave; fermato Cristo secondo Levi?"],
["Echelon","Il satellite scoperto negli anni 70 in grado di intercettare ogni forma di comunicazione"],
["Edam","Qual &egrave; la citta' dell'Olanda che da il nome al tipico formaggio ricoperto da cera rossa?"],
["edoardo bennato","Cantante di: SONO SOLO CANZONETTE"],
["edy","Il nome del robottino aiutante di archimede"],
["elefante","Insieme alla farfalla in una canzone di Zarrillo"],
["elena","La madre dell'imperatore Costantino"],
["elio","Il pi&ugrave; leggero dei gas nobili"],
["Emerson Fittipaldi","Chi &egrave; stato il primo brasiliano a diventare campione nel mondo di Formula 1 (Nome e Cognome)?"],
["endecasillabo","Il verso del sonetto"],
["enigma","Macchina cifrante tedesca usata ai tempi della seconda guerra mondiale"],
["enrico","Il Mentana giornalista italiano"],
["enrico papi","Ha condotto 'Sarabanda' su Italia 1"],
["enzo","Il famoso Ferrari della formula uno"],
["enzo iachetti","Chi conduce 'Striscia la notizia' insieme ad Ezio Greggio"],
["ercolano","La citt&ugrave; romana distrutta dall'eruzione del vesuvio"],
["eric","il nome del regista Rohmer"],
["erode","Chi fu il re che cercò di uccidere il fanciullino Ges&ugrave;?"],
["erodoto","Fu detto il 'padre della storia'"],
["eros ramazzotti","Cantante di: ADESSO TU"],
["esmeralda","La zingara del 'Notre dame de Paris'"],
["est","Il sole sorge a…"],
["estate","La stagione subito dopo la primavera"],
["evening","Sera in inglese"],
["express","I pony a cui si affidano le spedizioni"],
     

    ],   
    "f":[                
       ["fabrizio de andre","Cantante di: RIMINI"],
["fat man","Nome della prima bomba al plutonio sperimentata da Oppenheimer"],
["fausto","Il nome di Leali cantante italiano"],
["fe","Simbolo del Ferro"],
["fede","L'Emilio giornalista italiano"],
["femmina","Sesso opposto di Maschio"],
["fermo","Primo nome di Renzo nei 'Promessi Sposi'"],
["fiorella","Il nome della Mannoia"],
["Firenze","In quale citta' per entrare nel Battistero potete passare attraverso la Porta del Paradiso?"],
["firenze","La citt&ugrave; di Donatello"],
["flaiano","Ennio scrittore e sceneggiatore con Fellini"],
["fleming","Scopre la penicillina"],
["fornaciari","Il Cognome di Zucchero"],
["franco battiato","Cantante di: Cuccuruccucu Paloma"],
["fred bongusto","Cantante di: UNA ROTONDA SUL MARE"],
["frumento","L'altro nome del grano"],






    ],   
    "g":[      
        ["gruber","La rossa giornalista televisiva (cognome)"],
       ["Galles","In quale paese &egrave; nato l'attore Ray Milland?"],
["gambadilegno","Il nemico giurato di Topolino"],
["gastone","Paperino sta alla sfiga come lui sta alla fortuna"],
["ge","Simbolo del Germanio"],
["Gelli","Fondatore della loggia massonica in Italia(cognome)"],
["george","Il nome di Lucas il regista"],
["geronimo","Grande capo indiano"],
["ghigliottina","Fu utilizzata a lungo durante la rivoluzione francese"],
["giacomo","Giovanni Aldo e..."],
["gianna","La Nannini cantante toscana"],
["gianni morandi","Cantante di: SCENDE LA PIOGGIA"],
["giasone","L'eroe mitologico del vello d'oro"],
["ginestra","La pianta gialla cantata dal Leopardi"],
["gino paoli","Cantava 'Sapore di Sale'"],
["gino paoli","Cantava 'Eravamo quattro amici al bar'"],
["gino paoli","Cantante di: IL CIELO IN UNA STANZA"],
["giorgia","Cantante di: COME SAPREI"],
["giorgio","Il compianto cantante Gaber"],
["Giotto","Quale di questi artisti &egrave; considerato il principale precursore del Rinascimento? Giotto Michelangelo Bramante"],
["giovanni xxiii","Il papa che convocò il Concilio Vaticano II"],
["giove","Callisto ed Europa sono lune di che pianeta?"],
["giove","come si chiama il pi&ugrave; grande pianeta del sistema solare"],
["gnocchi","Il Gene comico italiano"],
["grigio","colore della pelliccia dei cincill&ugrave; ?"],
["guareschi","Ha scritto 'Don Camillo'"],
["guglielmo marconi","Nel 1901 effettuò la prima trasmissione radio"]    ,
    ],   
    "h":[                
      
["halley","Questa cometa appare ogni 76.3 anni"],
["harrison","Il George dei beatles"],
["harry potter","Il celebre mago della Rowling"],
["he","Simbolo del Elio"],
["helsinki","capitale della FINLANDIA"],
["hf","Simbolo del Afnio"],
["Hillary","Scalò per la prima volta l'Everest nel 1953"],
["hindenburg","Il nome del dirigibile esploso nel 1937 a Lakehurst"],
["HTTP","Il protocollo utilizzato dai Borwser"],
],
    "i":[
    
["Idaho","Boise &egrave; la capitale di quale stato degli USA?"],
["igloo","La casa degli Eschimesi"],
["il cairo","Capitale dell'Egitto"],
["il fiato","Indovinello: E' leggero come una piuma, eppure nessun uomo,  per quanto robusto, può trattenenerlo per pi&ugrave; di 5 minuti"],
["Indians","Completa il nome di questa sqadra di baseball:I Cleveland...?"],
["irene grandi","Cantante di: IN VACANZA DA UNA VITA"],
["isaia","Quale profeta predisse che il Cristo sarebbe nato da una vergine?"],
["israele","vinse la guerra dei sei giorni"],
["itaca","Di quale isola era re Ulisse"],
["itaca","L'isola di Ulisse"]  ,
    ],
    "l":[
     
["La tempesta","Quale opera di Shakespeare comincia con uba burrasca sul mare?"],
["laden","Il Bin diventato famoso per l'attentato a New York"],
["lambisci","Congiuntivo imperfetto di lambire"],
["lateranensi","I patti firmati nel 1911 tra Italia e Chiesa Cattolica"],
["laura","Il nome della Pausini"],
["legolas","Elfo nel 'Signore degli Anelli'"],
["libro","Quello della giungla &egrave; un film della Disney"],
["Lichtenstein","Quale americano ingrandisce fumetti realizzandone quadri (cognome)?"],
["lisbona","Capitale del Portogallo"],
["litfiba","Cantante di: REGINA DI CUORI"],
["litiganti","Fra i due il terzo gode"],
["little big horn","Il Vi fu sconfitto il Generale Custer"],
["little boy","Nome della bomba che fu sganciata su Hiroshima"],
["livio","Gloriam qui spreverit veram habebit (Chi disprezza la gloria otterÃ  quella vera)"],
["loredana","Il nome della Bert&egrave;"],
["lorella","La Cuccarini"],
["loren","Il cognome della Sofia 'prosperosa' attrice italiana"],
["louvre","Vi si trova la 'Gioconda' di Leonardo"],
["luca carboni","Cantante di: CI VUOLE UN FISICO BESTIALE"],
["luciano ligabue","Cantante di: CERTE NOTTI"],
["lucignolo","L'amico scapestrato di Pinocchio"],
["lucio battisti","Cantante di: IL MIO CANTO LIBERO"],
["lucio dalla","Insieme a Gianni Morandi cantava 'vita'"],
["lucio dalla","Cantante di: 4 MARZO 1943"],
["luisa","La bella Corna conduttrice e cantante italiana"],
["luna","Le maree sugli oceani della terrasono create dalla tirata gravitazionale dellla ____"],
["Lussemburgo","Quale nazione &egrave; al 170esimo posto al mondo per superficie, ma al terzo in Europa per attivita' commerciali?"],
["luther king","Il Martin che fu ucciso il 4 aprile 1968"]  
    ],
    "m":[
       
["madonna","Chi canta 'Like a Virgin'"],
["madrid","SPAGNA"],
["mali","Non tutti vengono per nuocere"],
["mancini","Insieme a Vialli nella sampdoria e ora allenatore"],
["mannoia","La Fiorella cantante italiana"],
["mannoia","La Fiorella cantante italiana"],
["marco polo","Scrisse 'Il milione'"],
["maria","Quale &egrave; il nome della prima figlia di Renzo e Lucia nei 'Promessi Sposi'"],
["maria de filippi","La moglie di maurizio costanzo"],
["marie","La Curie che nel 1902 isolÃ² il radio"],
["marshall","Il piano americano che sostenne l'Europa dopo la seconda guerra mondiale"],
["marte","Phobos e Deimos sono lune di che pianeta?"],
["marte","Phobos &egrave; una luna di che pianeta?"],
["marte","Il quarto pianeta dal sole &egrave; _______"],
["martin","Il nome di Luther King pastore battista"],
["marylin","L'indimenticata monroe"],
["marylin monroe","Interpretava agli uomini piacciono le bionde"],
["massacro","A Fort Alamo ve ne fu uno famoso"],
["massimo ranieri","Cantante di: ROSE ROSSE"],
["massimo ranieri","Vinse Sanremo con 'Perdere l amore'"],
["mastro ciliegia","RegalÃ² il tronco a Geppetto"],
["matteo","Come si chiamava l'apostolo detto 'il pubblicano'?"],
["mercurio","Il pianeta piÃ¹ vicino al sole &egrave;_________"],
["mg","Simbolo del Magnesio"],
["mia","Il nome della Martini cantante italiana"],
["michea","Quale profeta predisse in quale cittÃ  sarebbe nato il Cristo?"],
["michelle hunziker","L'ex moglie di Eros Ramazzotti"],
["midollo","PuÃ² essere osseo e spinale"],
["midriasi","Come &egrave; detto il fenomeno per il quale la pupilla si dilata?"],
["milza","Se corri tanto ti fa male"],
["mina","Cantante di: PAROLE PAROLE"],
["minosse","Il padre del Minotauro"],
["mio fratello","Chi &egrave; il figlio di tuo padre se non sei tu"],
["miopia","Indovinelli: PiÃ¹ cresce, meno si vede"],
["mo","Simbolo del Molibdeno"],
["monghidoro","Vi &egrave; nato Gianni Morandi"],
["monghidoro","Vi &egrave; nato Gianni Morandi"],
["montanelli","Indro firma del giornalismo italiano"],
["monte","Il Bianco &egrave; il piÃ¹ alto d'Europa"],
["montgomery","Capitali degli U.S.A. : Alabama"],
["mosca","capitale della Russia."],
["mosto","Succo ricavato dalla spremitura dell'uva"],
    ],
    "n":[
     
["nashville","Capitali degli U.S.A. : Tennessee"],
["nato","North Atlantic Treaty Organization alias..."],
["naumachia","Antico spettacolo di combattimento navale"],
["nautilus","Il sommergibile di ventimila leghe sotto i mari"],
["Nefertari","Moglie di Ramsete II"],
["nelson","Ammiraglio della battaglia di Trafalgar"],
["neozelandese","Lo scalatore Hillary dell'Everest era di nazionalitÃ "],
["nettuno","Da 1979 fino a 2000 il pianeta piÃ¹ distante dalla terra era ________"],
["new york","Dove &egrave; nato Mike Bongiorno?"],
["nino","Il D'Angelo della canzone italiana"],
["nizza","Dove &egrave; nato Garibaldi"],
["nomadi","Cantante di: CANZONE PER UN' AMICA"],
["norimberga","Il processo che si tenne dopo la fine della seconda guerra mondiale"],
["numa pompilio","Secondo re di Roma"],
["nuova zelanda","Peter Jackson vi ha girato il suo 'Signore degli anelli'"], 
    ],
    "o":[
       
["obiettore","Quello di coscenza &egrave; contrario al servizio militare"],
["offerto","Paricipio passato di offrire"],
["olimpo","Era sede degli dei greci"],
["olivia","Findanzata di Braccio di Ferro"],
["orazio","Il fidanzato di clarabella"],
["orbita","Il termine per il percorso seguito da un corpo nello spazio"],
["orbite","Le rotte dei veicoli spaziali"],
["Orecchio","In che parte del nostro corpo si trova l'organo del Corti?"],
["oreste","Il celebre comico Lionello"],
["organizzazione nazioni unite","Cosa significa O.N.U."],
["ornella","Il nome della Vanoni"],
["oro incenso mirra","Quali doni offersero i magi d'Oriente al fanciullino GesÃ¹?"],
["orsa maggiore","Quello che &egrave; il significato del nome della costellazione Ursa Major"],
["orsa minore","Quello che &egrave; il significato del nome della costellazione Ursa Minor"],
["orus","Dio egizio raffigurato come un falco"],
["osea","Quale profeta predisse che Dio avrebbe chiamato il suo figliuolo fuori dall'Egitto?"],
["oslo","NORVEGIA"],
["otto","Quanti cilindri ha un V-8"],
["ottovolante","L'altro nome delle montagne russe"],
["Ovale","Come &egrave; chiamato comunemente un pallone da rugby?"],
    ],
    "p":[
      
["palpito","Battito di cuore"],
["panatta","Adriano ci fece vincere la 'Coppa Davis'"],
["pancreas","Organo che secerne l'insulina"],
["paola e chiara","Cantante di: AMICI COME PRIMA"],
["paolo","Il rossi campione del mondo della nazionale nel 1982"],
["Paolo III","Il papa che indisse il Concilio di Trento"],
["parigi","CittÃ  degli Champs Elysees"],
["parigi","Place della Concorde si trova a"],
["parigi","Il Louvre si trova a"],
["parigi","Dove si trova la tompa di Napoleone"],
["parigi","Vi scorre la senna"],
["parigi","La Sorbona ne &egrave; la sua universitÃ "],
["parigi","La cittÃ  di Notre Dame"],
["parlante","Lo era il grillo di Pinocchio"],
["parotide","La malattia infantile detta 'orecchioni'"],
["pb","Simbolo del Piombo"],
["penelope","La moglie di Ulisse"],
["penelope","Tesseva la mitica tela su Itaca"],
["pennello","Serve per farsi la barba con la schiuma"],
["persona","Individuo"],
["peter jackson","Il regista del 'Signore degli Anelli'"],
["peter parker","Spider Man nella vita di tutti giorni"],
["piemonte","regioni di provenienza dei vini : BARBARESCO"],
["piemonte","regioni di provenienza dei vini : CHIANTI"],
["piemonte","regioni di provenienza dei vini : LANGHE"],
["pifferaio","In una favola libero la cittÃ  dai topi"],
["pino daniele","Cantante di: TERRA MIA"],
["pinocchio","Geppetto era suo padre"],
["piovra","Polipo di grandi dimensioni"],
["pipino","Uno degli hobbit compagni di avventura di Frodo"],
["pippo baudo","Katia Ricciarelli ne &egrave; la moglie"],
["pirandello","Scrisse il 'Fu Mattia Pascal'"],
["plotone d'esecuzione","Galeazzo Ciano ci finÃ¬ davanti dopo il processo"],
["poirot","Il detective blega di Agatha Christie"],
["polare","la stella che indica il nord &egrave; nota come ________"],
["polifemo","Il nome del ciclope dell'Odissea incontrato da Ulisse"],
["Pollock","Per quale artista fu coniato il termine 'Action painting'(cognome)?"],
["porta pia","La Breccia aperta a Roma nel 1870"],
["praga","REP. CECA"],
["pregadio","Roberto maestro della 'Corrida'"],
["presepe","Le statuine di natale lo realizzano"],
["Primavera","In quale stagione si svolge sogno di una notte di mezz'estate?"],
["primavera","L'equinozio primaverile &egrave; l'inizio di ________"],
["primavera","La celebre 'stagione' di praga"],
["proietti","Gigi, regista di 'full monty' a teatro"],
["Puffi","Quali personaggi dei cartoni animati vivono in case fatte a forma di fungo?"],
["puffi","Gli gnomi azzurri dei cartoni animati"],
["Punkreas","Chi canta la canzone 'Canapa'?"], 
        ["pappalardo","Cantante di: RICOMINCIAMO (cognome)"],
["pausini","Cantante di: NON C'E'"]

    ],
    "q":[
     
["quaid","Il Dennis interprete di 'Lontano dal Paradiso'"],
["quartieri","Quelli spagnoli sono una zona di Napoli"],
["quasimodo","Il nome del 'gobbo' di notre dame"],
["quirinalista","Giornalista che segue il capo dello stato"],
    ],
    "r":[
      
["ramazzotti","L'Eros cantante italiano"],
["rana","Il Giovanni dei tortellini"],
["rapa","Qual &egrave; l'ortaggio nazionale della Scozia?"],
["rapallo","In quale cittÃ  ligure vi fu nel 1922 il trattato tra Russia e Germania"],
["rasoio","Lo si usa per radersi"],
["recessione","Ristagno degli affari e dell'attivitÃ  economica"],
["remi","Li tira in barca chi rinuncia ad un impresa"],
["renato zero","Sono suoi fans i 'sorcini'"],
["resegone","Celebre monte dei 'Promessi Sposi'"],
["riccardo cocciante","Cantante di: BELLA SENZ'ANIMA"],
["richard gere","Era 'L ufficiale gentiluomo'"],
["richmond","Capitali degli U.S.A. : Virginia"],
["risaia","Un campo che si coltiva... allagandolo"],
["rna","Acido ribonucleico"],
["roberto benigni","Regista di 'La vita &eacute bella'"],
["roberto vecchioni","Cantante di: VOGLIO UNA DONNA"],
["roman","Il Polanski celebre regista"],
["romolo","Primo re di Roma"],
["rosa","Era blu quella di Zarrillo"],
["rossetto","Lo mettono le donne sulle labbra"],
    ],
    "s":[
     
["sacchi","L'Arrigo allenatore del milan e della nazionale"],
["Salce","Luciano, che ha diretto la Sandrelli nel 'Federale' -con la S?"],
["sam","Uno degli hobbit compagni di avventura di Frodo"],
["sandro","Il nome del compianto presidente della repubblica Pertini"],
["sant' elena","Vi morÃ¬ Napoleone"],
["Santa Rosalia","Il santo patrono di Palermo"],
["saturno","Come si chiama il secondo piÃ¹ grande pianeta del sistema solare"],
["saturno","Titan &egrave; una luna di che pianeta?"],
["saudita","L'Arabia ricca di petrolio"],
["scala","Delia inimitabile regina del varietÃ "],
["scherlock holmes","Watson ne era il braccio destro"],
["Sciascia","Chi &egrave; il Leonardo di Recalmuto?"],
["scotti","Il Jerry di 'Passaparola'"],
["scultura","In quale delle seguenti forme d'arte viene utilizzata la tecnica detta 'a cera persa'?"],
["Sculture","Cos'&egrave; la gipsoteca? Una raccolta diâ€¦."],
["se","Simbolo del Selenio"],
["se","Simbolo del Selenio"],
["servio tullio","Sesto di Roma"],
["sessanta","Ci sono ___secondi in 1 minuto"],
["sette","Quanti sono i giocatori di una squadra di pallamano?"],
["shaggy","Cantante di: IT WASN'T ME"],
["siena","In quale cittÃ  italiana si trova il dente di Santa Caterina?"],
["sigaretta","Indovinelli: Piu' la tiri, piu'si accorcia"],
["silvio","Il nome di Berlusconi"],
["silvio berlusconi","Ha creato il termine mi consenta"],
["silvio pellico","Scrisse 'Le mie Prigioni'"],
["sinai","Sulla sua cima secondo la BibbiÃ  Mos&egrave; ricevette i 10 comandamenti"],
["snoopy","Il cane di Charlie Brown"],
["sofia","Il nome della Loren"],
["sophia","Il nome della Loren"],
["Sorbona","L'UniversitÃ  piÃ¹ prestigiosa di Parigi"],
["sordi","L'Albertone nazionale"],
["spider man","Peter Parker non nella vita quotidiana"],
["Sputnik","Il primo satellite artificiale in orbita intorno alla terra"],
["sputnik","Il nome del primo statellite sovietico (1957)"],
["Stalin","Quale dittatore &egrave; morto nel 1953 in Unione Sovietica?"],
["stella cometa","Secondo il vangelo indicava la grotta dove nacque GesÃ¹"],
["stilografica","Che tipo di penna inventÃ² Lewis E. Waterman?"],
["storione","Indovinelli: Come si chiama l'insegnante di storia dei pesci ?"],
["strasburgo","Ha sede il parlamento europeo"],
["sumeri","Popolo dell'antichitÃ  che precedette gli Egizi"],  
    ],
    "t":[
            
        
["ta","Simbolo del Tantalio"],
["talk show","Tipo di programma televisivo con dibattito"],
["tarquinio il superbo","Settimo re di Roma"],
["tarquinio prisco","Quinto re di Roma"],
["tavola","Aggiungi un posto a..."],
["te","Simbolo del Tellurio"],
["teatro","Lo &egrave; la Scala di Milano"],
["Tebe","Capitale dell'antico Egitto durante la XI dinnastia"],
["telaio","La struttura della bicicletta"],
["telemaco","Il nome del figlio di Ulisse"],
["teo","Il nome di Teocoli"],
["Terence Hill","Fa coppia con Bud Spencer"],
["terra di mezzo","La 'Terra' del signore degli anelli"],
["teseo","Uccise il minotauro"],
["teseo","Arianna ne era innamorata"],
["testa","Dove sono gli organi riproduttivi del serpente?"],
["tex","Il pistolero piÃ¹ famoso di Sergio Bonelli"],
["ticino","Il nome del fiume che attraversa Pavia"],
["tiro","Quello mancino &egrave; una vera birbonata"],
["tiziano ferro","Cantante di: ROSSO RELATIVO"],
["tolkien","Ha scritto il signore degli anelli"],
["torino","Vi si trova la mole antonelliana"],
["toro","Era 'seduto' ma faceva il capo indiano"],
["toro seduto","grande capo indiano"],
["tre","Qunate medaglie ha vinto Di Biasi alle olimpiadi?"],
["tre","Quanti libri sono in una trilogia"],
["tre","Quanti erano i magi che visitarono GesÃ¹"],
["trecentosessantasei","Quanti giorni sono in un anno bisestile"],
["tullo ostilio","Terzo re di Roma"],
["turchina","La fata di 'Pinocchio'"],
    ],
    "u":[   
["ugo foscolo","Ha scritto i 'Sepolcri'"],
["ulisse","Telemaco ne era il figlio"],
["umberto tozzi","Cantante di: GLI ALTRI SIAMO NOI"],
["umberto tozzi","Cantante di: GENTE DI MARE"],
["umberto tozzi","Cantava insieme a Morandi e a Ruggeri 'Si pu&oacute dare di pi&uacute'"],
["umbria","Quale &egrave; l'unica regione dell'Italia Centrale non bagnata dal mare"],
["universale","Giudizio della cappella sistina"],
["uovo","Indovinelli: Piu' &eacute caldo, piu' &eacute fresco. Cosa &eacute?"],
["urano","Ariel &eacute un satellite di che pianeta nel sistema solare"],
["utensile","Attrezzo strumento di lavoro"], 
    ],
    "v":[
        
["Vaduz","Quale &egrave; la capitale del Liechtenstein?"],
["valeria","La giunonica Marini ex-compagna di Cecchi Gori"],
["valerio","Il nome di Staffelli inviato di 'Striscia la Notizia'"],
["vanoni","Ornella cantante italiana"],
["vasco rossi","Cantante di: UNA CANZONE PER TE"],
["vate","Cosi era detto D'Annunzio?"],
["venerdi","Il nome del servitore di Robinson Crusoe"],
["venere","Il diametro di questo pianeta &egrave; molto uguale a quello di un altro"],
["veneto","regioni di provenienza dei vini : AMARONE"],
["venezia","La cittÃ  del ponte di rialto"],
["Versailles","Dove si trova la sala degli specchi?"],
["vesuvio","Vulcano della Campania"],
["via col vento","Vi furono attori Clark Gable e Vivien Leigh (domani e' un altro giorno)..."],
["vialli","Mancini faceva coppia con lui nella sampdoria"],
["voce","Indovinello: Chi la perde non può dirlo a nessuno"],
["volsci","Coriolano li guid&oacute contro Roma"], 
    ],
    "z":[
       
   
["zampillo","Sottile getto d'acqua che sgorga"],
["zebedeo","Come si chiamava il padre degli apostoli Giovanni e Giacomo?"],
["zero","Venere ha quante lune'"],
["zibibbo","Qual &egrave; la famosa varieta' di uva bianca coltivata in sicilia?"],
    ]
}